#!/bin/bash

# establish the base directory that I'm working out of
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Copying Blair's dotfiles from $BASEDIR..."

# TODO: Add conditional statements to add to existing dotfiles
# rather than use ln -sf to force override. May break things
# on some systems.
#
# Good practice will be to have simple "top level" dotfiles,
# and store more detailed options in secondary files, such
# as ~/.bash_aliases

# vim
ln -s ${BASEDIR}/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim ~/.vim

# bash
ln -s ${BASEDIR}/bashrc ~/.bashrc
ln -s ${BASEDIR}/bash_aliases ~/.bash_aliases
ln -s ${BASEDIR}/inputrc ~/.inputrc
ln -s ${BASEDIR}/zshrc ~/.zshrc
ln -s ${BASEDIR}/bash_profile ~/.bash-profile

#git
ln -s ${BASEDIR}/gitconfig ~/.gitconfig

# terminator
mkdir ~/.config/terminator
ln -s ${BASEDIR}/terminator ~/.config/terminator/config

#i3
ln -s ${BASEDIR}/dotfiles/i3 ~/.config/i3

# espanso
ln -s ${BASEDIR}/espanso ~/.config/espanso

# Download submodules
echo "Getting submodules..."
cd $BASEDIR
git submodule update --init --remote

# TODO: Consider installing additional packages such as fzf 
# to remote machines
