#!/bin/bash

# establish the base directory that I'm working out of
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Copying files from $BASEDIR..."

# vim
ln -s ${BASEDIR}/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim ~/.vim

# bash
ln -s ${BASEDIR}/bashrc ~/.bashrc
ln -s ${BASEDIR}/inputrc ~/.inputrc

#git
ln -s ${BASEDIR}/gitconfig ~/.gitconfig

