#!/bin/bash

# establish the base directory that I'm working out of
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Copying Blair's dotfiles from $BASEDIR..."

# vim
ln -sf ${BASEDIR}/vimrc ~/.vimrc
ln -sf ${BASEDIR}/vim ~/.vim

# bash
ln -sf ${BASEDIR}/bashrc ~/.bashrc
ln -sf ${BASEDIR}/inputrc ~/.inputrc

#git
ln -sf ${BASEDIR}/gitconfig ~/.gitconfig

# Download submodules
echo "Getting submodules..."
cd $BASEDIR
git submodule update --init --remote
